### ISSUE TITLE
fatemanager激活站点失败: failed to add routing table

### ISSUE THREAD

**Issue by liuyanntes** [FederatedAI/FATE-Cloud#123]
fatemanager激活站点失败: failed to add routing table

---

[INFO] [2021-12-13 21:34:19,102] [47059:140168874948352] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba81a0160>, <peewee.Expression object at 0x7f7ba81a02b0>]
[INFO] [2021-12-13 21:34:21,909] [47059:140168874948352] - site_service.py[line:27]: site registrationLink decode info:http://10.45.47.142:9000--9999--kevhhnJb
[INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:37]: start save exchange info to rollsite
[INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:748]: write rollsite info:ip 10.10.178.147, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '10.45.47.142', 'is_secure': False, 'is_polling': False}]}}
[INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - roll_site.py[line:15]: get route table
[INFO] [2021-12-13 21:34:23,942] [47059:140168843478784] - apply.py[line:72]: start request cloud AuthorityApplied
[INFO] [2021-12-13 21:34:23,947] [47059:140168843478784] - request_cloud_utils.py[line:141]: start request uri:http://10.45.47.142:9000/cloud-manager/api/authority/applied, body:{'institutions': 'goods1'}, head:{'VERSION': 'v2', 'TIMESTAMP': '1639402463943', 'FATE_MANAGER_USER_ID': 'ec5e40d4275b4dbcaea07164500bd8d6', 'NONCE': '6293cb4e5c1911ecb3d7005056affcc1', 'FATE_MANAGER_APP_KEY': '1J4sxHiX', 'SIGNATURE': 'getpLsaYhKopG0nMyC2K7zzYSek='}
[INFO] [2021-12-13 21:34:24,073] [47059:140168843478784] - request_cloud_utils.py[line:159]: response:{"code":0,"msg":"Success!","data":{"scenarioType":"3","guestList":[],"hostList":[],"all":null,"total":0}}
[INFO] [2021-12-13 21:34:24,074] [47059:140168843478784] - apply.py[line:80]: request cloud success, return {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0}
[INFO] [2021-12-13 21:34:24,083] [47059:140168843478784] - db_operator.py[line:133]: update fields: {<ListField: AccountInfo.allow_instituions>: {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0}, <IntegerField: AccountInfo.role>: 1, <SmallIntegerField: AccountInfo.status>: 1, <BigIntegerField: AccountInfo.update_time>: 1639402464083, <DateTimeField: AccountInfo.update_date>: '2021-12-13 21:34:24'}
[INFO] [2021-12-13 21:34:24,084] [47059:140168843478784] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba8195e10>, <peewee.Expression object at 0x7f7ba81955c0>]
[INFO] [2021-12-13 21:34:24,914] [47059:140168874948352] - site_service.py[line:753]: write rollsite data failed
[ERROR] [2021-12-13 21:34:24,916] [47059:140168874948352] - api_utils.py[line:18]: (30001, 'failed to add routing table')
Traceback (most recent call last):
  File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 750, in update_all_rollsite_info
    write_site_route(rollsite_ip, rollsite_port, ROLL_SITE_KEY, site_route, str(party_id))
  File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 17, in write_site_route
    operator="get_route_table", overall_timeout=overall_timeout)
  File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 29, in roll_site_actuator
    _return, _call = stub.unaryCall.with_call(_packet, timeout=(overall_timeout/1000))
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1639402464.913262196","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/fatemanager/projects/FATE-Cloud/fate_manager/apps/site_app.py", line 32, in register_site
    data = site_service.register_fate_site(request_data)
  File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 40, in register_fate_site
    is_polling=request_data.get("pollingStatus"))
  File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 755, in update_all_rollsite_info
    raise Exception(RollsiteInfoStatusCode.Write_RollSite_Fail,f"failed to add routing table")
Exception: (30001, 'failed to add routing table')

**Comment by amenhub** [comment]
> fatemanager激活站点失败: failed to add routing table
> 
> [INFO] [2021-12-13 21:34:19,102] [47059:140168874948352] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba81a0160>, <peewee.Expression object at 0x7f7ba81a02b0>] [INFO] [2021-12-13 21:34:21,909] [47059:140168874948352] - site_service.py[line:27]: site registrationLink decode info:http://10.45.47.142:9000--9999--kevhhnJb [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:37]: start save exchange info to rollsite [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:748]: write rollsite info:ip 10.10.178.147, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '10.45.47.142', 'is_secure': False, 'is_polling': False}]}} [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - roll_site.py[line:15]: get route table [INFO] [2021-12-13 21:34:23,942] [47059:140168843478784] - apply.py[line:72]: start request cloud AuthorityApplied [INFO] [2021-12-13 21:34:23,947] [47059:140168843478784] - request_cloud_utils.py[line:141]: start request uri:http://10.45.47.142:9000/cloud-manager/api/authority/applied, body:{'institutions': 'goods1'}, head:{'VERSION': 'v2', 'TIMESTAMP': '1639402463943', 'FATE_MANAGER_USER_ID': 'ec5e40d4275b4dbcaea07164500bd8d6', 'NONCE': '6293cb4e5c1911ecb3d7005056affcc1', 'FATE_MANAGER_APP_KEY': '1J4sxHiX', 'SIGNATURE': 'getpLsaYhKopG0nMyC2K7zzYSek='} [INFO] [2021-12-13 21:34:24,073] [47059:140168843478784] - request_cloud_utils.py[line:159]: response:{"code":0,"msg":"Success!","data":{"scenarioType":"3","guestList":[],"hostList":[],"all":null,"total":0}} [INFO] [2021-12-13 21:34:24,074] [47059:140168843478784] - apply.py[line:80]: request cloud success, return {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0} [INFO] [2021-12-13 21:34:24,083] [47059:140168843478784] - db_operator.py[line:133]: update fields: {<ListField: AccountInfo.allow_instituions>: {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0}, <IntegerField: AccountInfo.role>: 1, <SmallIntegerField: AccountInfo.status>: 1, <BigIntegerField: AccountInfo.update_time>: 1639402464083, <DateTimeField: AccountInfo.update_date>: '2021-12-13 21:34:24'} [INFO] [2021-12-13 21:34:24,084] [47059:140168843478784] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba8195e10>, <peewee.Expression object at 0x7f7ba81955c0>] [INFO] [2021-12-13 21:34:24,914] [47059:140168874948352] - site_service.py[line:753]: write rollsite data failed [ERROR] [2021-12-13 21:34:24,916] [47059:140168874948352] - api_utils.py[line:18]: (30001, 'failed to add routing table') Traceback (most recent call last): File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 750, in update_all_rollsite_info write_site_route(rollsite_ip, rollsite_port, ROLL_SITE_KEY, site_route, str(party_id)) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 17, in write_site_route operator="get_route_table", overall_timeout=overall_timeout) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 29, in roll_site_actuator _return, _call = stub.unaryCall.with_call(_packet, timeout=(overall_timeout/1000)) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 957, in with_call return _end_unary_response_blocking(state, call, True, None) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED details = "Deadline Exceeded" debug_error_string = "{"created":"@1639402464.913262196","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
> 
> > 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise raise value File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/fatemanager/projects/FATE-Cloud/fate_manager/apps/site_app.py", line 32, in register_site data = site_service.register_fate_site(request_data) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 40, in register_fate_site is_polling=request_data.get("pollingStatus")) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 755, in update_all_rollsite_info raise Exception(RollsiteInfoStatusCode.Write_RollSite_Fail,f"failed to add routing table") Exception: (30001, 'failed to add routing table')

hi bro,
when i tried to activate the site in fate-manager, the same exception happened as you, and the difference with you is that this line of exception information appeared in the debug log. 

i don't quite understand it, can someone tell me how to do it? thanks.

[INFO] [2022-02-16 15:36:46,795] [8385:140039681992448] - site_service.py[line:27]: site registrationLink decode info:http://10.9.20.233:8998--10000--juhfOrO1
[INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:37]: start save exchange info to rollsite
[INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:748]: write rollsite info:ip 192.168.0.3, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '192.168.0.3', 'is_secure': True, 'is_polling': True}]}}
[INFO] [2022-02-16 15:36:46,797] [8385:140039681992448] - roll_site.py[line:15]: get route table
[INFO] [2022-02-16 15:36:46,905] [8385:140039681992448] - roll_site.py[line:31]: **b'getRouteTable failed. Token verification failed.'**
[INFO] [2022-02-16 15:36:46,906] [8385:140039681992448] - site_service.py[line:753]: write rollsite data failed
[ERROR] [2022-02-16 15:36:46,907] [8385:140039681992448] - api_utils.py[line:18]: (30001, 'failed to add routing table')

**Comment by pizhicheng** [comment]
> > fatemanager激活站点失败: failed to add routing table
> > [INFO] [2021-12-13 21:34:19,102] [47059:140168874948352] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba81a0160>, <peewee.Expression object at 0x7f7ba81a02b0>] [INFO] [2021-12-13 21:34:21,909] [47059:140168874948352] - site_service.py[line:27]: site registrationLink decode info:http://10.45.47.142:9000--9999--kevhhnJb [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:37]: start save exchange info to rollsite [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:748]: write rollsite info:ip 10.10.178.147, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '10.45.47.142', 'is_secure': False, 'is_polling': False}]}} [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - roll_site.py[line:15]: get route table [INFO] [2021-12-13 21:34:23,942] [47059:140168843478784] - apply.py[line:72]: start request cloud AuthorityApplied [INFO] [2021-12-13 21:34:23,947] [47059:140168843478784] - request_cloud_utils.py[line:141]: start request uri:http://10.45.47.142:9000/cloud-manager/api/authority/applied, body:{'institutions': 'goods1'}, head:{'VERSION': 'v2', 'TIMESTAMP': '1639402463943', 'FATE_MANAGER_USER_ID': 'ec5e40d4275b4dbcaea07164500bd8d6', 'NONCE': '6293cb4e5c1911ecb3d7005056affcc1', 'FATE_MANAGER_APP_KEY': '1J4sxHiX', 'SIGNATURE': 'getpLsaYhKopG0nMyC2K7zzYSek='} [INFO] [2021-12-13 21:34:24,073] [47059:140168843478784] - request_cloud_utils.py[line:159]: response:{"code":0,"msg":"Success!","data":{"scenarioType":"3","guestList":[],"hostList":[],"all":null,"total":0}} [INFO] [2021-12-13 21:34:24,074] [47059:140168843478784] - apply.py[line:80]: request cloud success, return {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0} [INFO] [2021-12-13 21:34:24,083] [47059:140168843478784] - db_operator.py[line:133]: update fields: {<ListField: AccountInfo.allow_instituions>: {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0}, <IntegerField: AccountInfo.role>: 1, <SmallIntegerField: AccountInfo.status>: 1, <BigIntegerField: AccountInfo.update_time>: 1639402464083, <DateTimeField: AccountInfo.update_date>: '2021-12-13 21:34:24'} [INFO] [2021-12-13 21:34:24,084] [47059:140168843478784] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba8195e10>, <peewee.Expression object at 0x7f7ba81955c0>] [INFO] [2021-12-13 21:34:24,914] [47059:140168874948352] - site_service.py[line:753]: write rollsite data failed [ERROR] [2021-12-13 21:34:24,916] [47059:140168874948352] - api_utils.py[line:18]: (30001, 'failed to add routing table') Traceback (most recent call last): File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 750, in update_all_rollsite_info write_site_route(rollsite_ip, rollsite_port, ROLL_SITE_KEY, site_route, str(party_id)) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 17, in write_site_route operator="get_route_table", overall_timeout=overall_timeout) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 29, in roll_site_actuator _return, _call = stub.unaryCall.with_call(_packet, timeout=(overall_timeout/1000)) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 957, in with_call return _end_unary_response_blocking(state, call, True, None) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED details = "Deadline Exceeded" debug_error_string = "{"created":"@1639402464.913262196","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
> > > 
> > 
> > 
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise raise value File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/fatemanager/projects/FATE-Cloud/fate_manager/apps/site_app.py", line 32, in register_site data = site_service.register_fate_site(request_data) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 40, in register_fate_site is_polling=request_data.get("pollingStatus")) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 755, in update_all_rollsite_info raise Exception(RollsiteInfoStatusCode.Write_RollSite_Fail,f"failed to add routing table") Exception: (30001, 'failed to add routing table')
> 
> hi bro, @pizhicheng when i tried to activate the site in fate-manager, the same exception happened as you, and the difference with you is that this line of exception information appeared in the debug log.
> 
> i don't quite understand it, can you tell me how to do it? thanks.
> 
> [INFO] [2022-02-16 15:36:46,795] [8385:140039681992448] - site_service.py[line:27]: site registrationLink decode info:http://192.168.0.3:8998--10000--juhfOrO1 [INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:37]: start save exchange info to rollsite [INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:748]: write rollsite info:ip 192.168.0.3, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '192.168.0.3', 'is_secure': True, 'is_polling': True}]}} [INFO] [2022-02-16 15:36:46,797] [8385:140039681992448] - roll_site.py[line:15]: get route table [INFO] [2022-02-16 15:36:46,905] [8385:140039681992448] - roll_site.py[line:31]: **b'getRouteTable failed. Token verification failed.'** [INFO] [2022-02-16 15:36:46,906] [8385:140039681992448] - site_service.py[line:753]: write rollsite data failed [ERROR] [2022-02-16 15:36:46,907] [8385:140039681992448] - api_utils.py[line:18]: (30001, 'failed to add routing table')

Maybe, there is no authority for your machine to visit rollsite.  Try to add local ip into white list in rollsite.
Rollsite configuration file:  fate/eggroll/conf/eggroll.properties.
Edit properties like below:
`eggroll.rollsite.route.table.whitelist=192.168.0.1,192.168.0.2`
And then restart rollsite with command:
`fate/eggroll/conf/eggroll.sh rollsite restart`

**Comment by amenhub** [comment]
> 

thanks for the reply, i tried it and it still doesn't work..

**Comment by amenhub** [comment]
> > > fatemanager激活站点失败: failed to add routing table
> > > [INFO] [2021-12-13 21:34:19,102] [47059:140168874948352] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba81a0160>, <peewee.Expression object at 0x7f7ba81a02b0>] [INFO] [2021-12-13 21:34:21,909] [47059:140168874948352] - site_service.py[line:27]: site registrationLink decode info:http://10.45.47.142:9000--9999--kevhhnJb [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:37]: start save exchange info to rollsite [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - site_service.py[line:748]: write rollsite info:ip 10.10.178.147, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '10.45.47.142', 'is_secure': False, 'is_polling': False}]}} [INFO] [2021-12-13 21:34:21,910] [47059:140168874948352] - roll_site.py[line:15]: get route table [INFO] [2021-12-13 21:34:23,942] [47059:140168843478784] - apply.py[line:72]: start request cloud AuthorityApplied [INFO] [2021-12-13 21:34:23,947] [47059:140168843478784] - request_cloud_utils.py[line:141]: start request uri:http://10.45.47.142:9000/cloud-manager/api/authority/applied, body:{'institutions': 'goods1'}, head:{'VERSION': 'v2', 'TIMESTAMP': '1639402463943', 'FATE_MANAGER_USER_ID': 'ec5e40d4275b4dbcaea07164500bd8d6', 'NONCE': '6293cb4e5c1911ecb3d7005056affcc1', 'FATE_MANAGER_APP_KEY': '1J4sxHiX', 'SIGNATURE': 'getpLsaYhKopG0nMyC2K7zzYSek='} [INFO] [2021-12-13 21:34:24,073] [47059:140168843478784] - request_cloud_utils.py[line:159]: response:{"code":0,"msg":"Success!","data":{"scenarioType":"3","guestList":[],"hostList":[],"all":null,"total":0}} [INFO] [2021-12-13 21:34:24,074] [47059:140168843478784] - apply.py[line:80]: request cloud success, return {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0} [INFO] [2021-12-13 21:34:24,083] [47059:140168843478784] - db_operator.py[line:133]: update fields: {<ListField: AccountInfo.allow_instituions>: {'scenarioType': '3', 'guestList': [], 'hostList': [], 'all': None, 'total': 0}, <IntegerField: AccountInfo.role>: 1, <SmallIntegerField: AccountInfo.status>: 1, <BigIntegerField: AccountInfo.update_time>: 1639402464083, <DateTimeField: AccountInfo.update_date>: '2021-12-13 21:34:24'} [INFO] [2021-12-13 21:34:24,084] [47059:140168843478784] - db_operator.py[line:134]: update filters: [<peewee.Expression object at 0x7f7ba8195e10>, <peewee.Expression object at 0x7f7ba81955c0>] [INFO] [2021-12-13 21:34:24,914] [47059:140168874948352] - site_service.py[line:753]: write rollsite data failed [ERROR] [2021-12-13 21:34:24,916] [47059:140168874948352] - api_utils.py[line:18]: (30001, 'failed to add routing table') Traceback (most recent call last): File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 750, in update_all_rollsite_info write_site_route(rollsite_ip, rollsite_port, ROLL_SITE_KEY, site_route, str(party_id)) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 17, in write_site_route operator="get_route_table", overall_timeout=overall_timeout) File "/fatemanager/projects/FATE-Cloud/fate_manager/controller/roll_site.py", line 29, in roll_site_actuator _return, _call = stub.unaryCall.with_call(_packet, timeout=(overall_timeout/1000)) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 957, in with_call return _end_unary_response_blocking(state, call, True, None) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.DEADLINE_EXCEEDED details = "Deadline Exceeded" debug_error_string = "{"created":"@1639402464.913262196","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
> > > > 
> > > 
> > > 
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last): File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise raise value File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/fatemanager/myenv/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/fatemanager/projects/FATE-Cloud/fate_manager/apps/site_app.py", line 32, in register_site data = site_service.register_fate_site(request_data) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 40, in register_fate_site is_polling=request_data.get("pollingStatus")) File "/fatemanager/projects/FATE-Cloud/fate_manager/service/site_service.py", line 755, in update_all_rollsite_info raise Exception(RollsiteInfoStatusCode.Write_RollSite_Fail,f"failed to add routing table") Exception: (30001, 'failed to add routing table')
> > 
> > 
> > hi bro, @pizhicheng when i tried to activate the site in fate-manager, the same exception happened as you, and the difference with you is that this line of exception information appeared in the debug log.
> > i don't quite understand it, can you tell me how to do it? thanks.
> > [INFO] [2022-02-16 15:36:46,795] [8385:140039681992448] - site_service.py[line:27]: site registrationLink decode info:http://192.168.0.3:8998--10000--juhfOrO1 [INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:37]: start save exchange info to rollsite [INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:748]: write rollsite info:ip 192.168.0.3, port 9370,key fate, route: {'default': {'default': [{'port': 9370, 'ip': '192.168.0.3', 'is_secure': True, 'is_polling': True}]}} [INFO] [2022-02-16 15:36:46,797] [8385:140039681992448] - roll_site.py[line:15]: get route table [INFO] [2022-02-16 15:36:46,905] [8385:140039681992448] - roll_site.py[line:31]: **b'getRouteTable failed. Token verification failed.'** [INFO] [2022-02-16 15:36:46,906] [8385:140039681992448] - site_service.py[line:753]: write rollsite data failed [ERROR] [2022-02-16 15:36:46,907] [8385:140039681992448] - api_utils.py[line:18]: (30001, 'failed to add routing table')
> 
> Maybe, there is no authority for your machine to visit rollsite. Try to add local ip into white list in rollsite. Rollsite configuration file: fate/eggroll/conf/eggroll.properties. Edit properties like below: `eggroll.rollsite.route.table.whitelist=192.168.0.1,192.168.0.2` And then restart rollsite with command: `fate/eggroll/conf/eggroll.sh rollsite restart`

By reading the code, i found the key in this log info refers to ROLL_SITE_KEY, but Rollsite configuration file: eggroll.properties is configured with exchange, `eggroll.rollsite.route.table.key=exchange`, is there any connection?

[INFO] [2022-02-16 15:36:46,796] [8385:140039681992448] - site_service.py[line:748]: write rollsite info:ip 192.168.0.3, port 9370,**key fate**, route: {'default': {'default': [{'port': 9370, 'ip': '192.168.0.3', 'is_secure': True, 'is_polling': True}]}}
