### ISSUE TITLE
The username or password error!

### ISSUE THREAD

**Issue by amenhub** [FederatedAI/FATE-Cloud#128]
when i try to add user in cloud-manager, it doesn't ask me for a password, but it prompts me that the username or password error, what's going on?
![1644975839(1)](https://user-images.githubusercontent.com/35909818/154180685-06e53242-11eb-49d8-99c8-6d346273ab8f.jpg)

**Comment by pizhicheng** [comment]
Cloud-Manager are not responsible for managing user accounts. We hope that users can develop their own account system to connect with their own company. You can directly write the username and password MD5  to the database table - **t_cloud_manager_origin_user**.
If you wanna to add a user **admin1** with password **admin** you can use the sql like below
Example: 
`INSERT INTO t_cloud_manager_origin_user (name,password) VALUES ("admin1","21232f297a57a5a743894a0e4a801fc3")`

**Comment by amenhub** [comment]
okay.....
but when i copy the link to fate-manager to activate it, how can i solve the exception prompted? thanks!
![image](https://user-images.githubusercontent.com/35909818/154184264-052d2e3d-2baa-4fa4-81c8-ce549b1fd7a1.png)

**Comment by amenhub** [comment]
thanks!
