### ISSUE TITLE
fate-cloud v1.3

### ISSUE THREAD

**Issue by zhihuiwan** [FederatedAI/FATE-Cloud#79]
fate manager :
1. rebuild code by python;
2. add job monitor module

**Comment by caohuachun** [comment]
cloud manager :
1. add federated authority
2. add federated fate site job monitor
3. cloud certificate dns name rule changes
4. check signature httpBody changes

**Comment by cold-code** [comment]
1.Fate-manager
a.Add job monitor module;
b.Change Site Cooperation API;
c.Optimize internationalization related code;

2.Fate-cloud
a.Add job monitor module;
b.Optimize internationalization related code;
c.Adjust part of the pop-up UI and page UI
